### PR TITLE
Ensuring permissions settings are maintained if container is recreated

### LINKED ISSUE #21: `rm auto_configure.php` causes crash after auto-config
Looks like by adding the second `rm auto_configure.php` [here](https://github.com/openemr/openemr-devops/blob/c6abcdab46eab77bcd1c53fa7aed2a186a07f857/docker-images/openemr/run_openemr.sh#L83), it's trying to remove the file twice. Removing it the first time seems likely to be sufficient, although I have to test the behavior of stopping and restarting a container to better understand which things will be persisted. Additionally, we may need to take some steps to properly persist the permissions that are done during autoconfig. Presently, they may be lost when a container is killed, but its site volume is preserved, and a new container is started in its place. The logical solution seems to be to move them into a separate 'if' block, checking only if `$CONFIG == 1` and then re-applying the permissions forcefully. That would honestly take care of both issues I think.

### PR DESCRIPTION
**Pull request by TheToolbox**
This also fixes #21

### CODE REVIEW

File: docker-images/openemr/run_openemr.sh [hunk 1]
```diff
@@ -32,7 +32,33 @@ auto_setup() {
...
+        echo "Couldn't set up. Any of these reasons could be what's wrong:"
+        echo " - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance"
+        echo " - MySQL is still starting up and wasn't ready for connection yet"
+        echo " - The Mysql credentials were incorrect"
+        sleep 1;
+    done
+    echo "Setup Complete!"
+fi
+
+if [ "$CONFIG" == "1" ]; then
```
Comment (bradymiller) [inline docker-images/openemr/run_openemr.sh]: Doesn't all the stuff also need to happen after the autoinstall?
(I think above if will skip that scenario)

Comment (TheToolbox) [reply docker-images/openemr/run_openemr.sh]: I double checked. It does correctly happen after autoinstall (since autoinstall now sets CONFIG again when it completes)

Comment (bradymiller) [reply docker-images/openemr/run_openemr.sh]: oh, that makes sense (forgot that a function doesn't limit scope of a variable in bash). looks good to go then.
